# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a46fd7576b4c88289fc3a917de7223cda49b82a03623059e2bca70a3c7d052e7361c82a8f6193fd60b3464f0fef4528b857b93cf7d51ba82a7b85b2853cf01d4

test:
  secret_key_base: 890769f3d9c14e6675db332387e2e0b9c988cf1766dd9a0b9636042bef1f6d20807db374bfb3b6f68d23e57b455ad88bb3445a1fcb3f3d61d9f9f88a98990de1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
